/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db;


import fi.istrange.traveler.db.tables.CardUser;
import fi.istrange.traveler.db.tables.GroupCard;
import fi.istrange.traveler.db.tables.PersonalCard;
import fi.istrange.traveler.db.tables.TravelerUser;
import fi.istrange.traveler.db.tables.UserCredentials;
import fi.istrange.traveler.db.tables.UserPhoto;
import fi.istrange.traveler.db.tables.records.CardUserRecord;
import fi.istrange.traveler.db.tables.records.GroupCardRecord;
import fi.istrange.traveler.db.tables.records.PersonalCardRecord;
import fi.istrange.traveler.db.tables.records.TravelerUserRecord;
import fi.istrange.traveler.db.tables.records.UserCredentialsRecord;
import fi.istrange.traveler.db.tables.records.UserPhotoRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GroupCardRecord> GROUP_CARD_PKEY = UniqueKeys0.GROUP_CARD_PKEY;
    public static final UniqueKey<PersonalCardRecord> PERSONAL_CARD_PKEY = UniqueKeys0.PERSONAL_CARD_PKEY;
    public static final UniqueKey<TravelerUserRecord> TRAVELER_USER_PKEY = UniqueKeys0.TRAVELER_USER_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CardUserRecord, GroupCardRecord> CARD_USER__CARD_USER_CARD_ID_FKEY = ForeignKeys0.CARD_USER__CARD_USER_CARD_ID_FKEY;
    public static final ForeignKey<CardUserRecord, TravelerUserRecord> CARD_USER__CARD_USER_USERNAME_FKEY = ForeignKeys0.CARD_USER__CARD_USER_USERNAME_FKEY;
    public static final ForeignKey<PersonalCardRecord, TravelerUserRecord> PERSONAL_CARD__PERSONAL_CARD_USERNAME_FK_FKEY = ForeignKeys0.PERSONAL_CARD__PERSONAL_CARD_USERNAME_FK_FKEY;
    public static final ForeignKey<UserCredentialsRecord, TravelerUserRecord> USER_CREDENTIALS__USER_CREDENTIALS_USERNAME_FKEY = ForeignKeys0.USER_CREDENTIALS__USER_CREDENTIALS_USERNAME_FKEY;
    public static final ForeignKey<UserPhotoRecord, TravelerUserRecord> USER_PHOTO__USER_CREDENTIALS_USERNAME_FKEY = ForeignKeys0.USER_PHOTO__USER_CREDENTIALS_USERNAME_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<GroupCardRecord> GROUP_CARD_PKEY = createUniqueKey(GroupCard.GROUP_CARD, "group_card_pkey", GroupCard.GROUP_CARD.ID);
        public static final UniqueKey<PersonalCardRecord> PERSONAL_CARD_PKEY = createUniqueKey(PersonalCard.PERSONAL_CARD, "personal_card_pkey", PersonalCard.PERSONAL_CARD.ID);
        public static final UniqueKey<TravelerUserRecord> TRAVELER_USER_PKEY = createUniqueKey(TravelerUser.TRAVELER_USER, "traveler_user_pkey", TravelerUser.TRAVELER_USER.USERNAME);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<CardUserRecord, GroupCardRecord> CARD_USER__CARD_USER_CARD_ID_FKEY = createForeignKey(fi.istrange.traveler.db.Keys.GROUP_CARD_PKEY, CardUser.CARD_USER, "card_user__card_user_card_id_fkey", CardUser.CARD_USER.CARD_ID);
        public static final ForeignKey<CardUserRecord, TravelerUserRecord> CARD_USER__CARD_USER_USERNAME_FKEY = createForeignKey(fi.istrange.traveler.db.Keys.TRAVELER_USER_PKEY, CardUser.CARD_USER, "card_user__card_user_username_fkey", CardUser.CARD_USER.USERNAME);
        public static final ForeignKey<PersonalCardRecord, TravelerUserRecord> PERSONAL_CARD__PERSONAL_CARD_USERNAME_FK_FKEY = createForeignKey(fi.istrange.traveler.db.Keys.TRAVELER_USER_PKEY, PersonalCard.PERSONAL_CARD, "personal_card__personal_card_username_fk_fkey", PersonalCard.PERSONAL_CARD.USERNAME_FK);
        public static final ForeignKey<UserCredentialsRecord, TravelerUserRecord> USER_CREDENTIALS__USER_CREDENTIALS_USERNAME_FKEY = createForeignKey(fi.istrange.traveler.db.Keys.TRAVELER_USER_PKEY, UserCredentials.USER_CREDENTIALS, "user_credentials__user_credentials_username_fkey", UserCredentials.USER_CREDENTIALS.USERNAME);
        public static final ForeignKey<UserPhotoRecord, TravelerUserRecord> USER_PHOTO__USER_CREDENTIALS_USERNAME_FKEY = createForeignKey(fi.istrange.traveler.db.Keys.TRAVELER_USER_PKEY, UserPhoto.USER_PHOTO, "user_photo__user_credentials_username_fkey", UserPhoto.USER_PHOTO.USERNAME);
    }
}
