/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.group_card_id_seq</code>
     */
    public static final Sequence<Long> GROUP_CARD_ID_SEQ = new SequenceImpl<Long>("group_card_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.personal_card_id_seq</code>
     */
    public static final Sequence<Long> PERSONAL_CARD_ID_SEQ = new SequenceImpl<Long>("personal_card_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
