package fi.istrange.traveler.resources;

import fi.istrange.traveler.api.UserAuthReq;
import io.swagger.annotations.Api;
import sun.reflect.generics.reflectiveObjects.NotImplementedException;

import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

/**
 * Created by arsenii on 4/9/17.
 */
@Path("/tokens")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@Api(value = "/tokens", tags = "tokens")
public class TokenResource {

    // TODO token DAO goes here as parameter
    public TokenResource() {}

    @POST
    public String authorizeUser(UserAuthReq userAuthReq) {
        // TODO generate token or update token's last access time here, return token generated by token DAO after verifying user credentials
        throw new NotImplementedException();
    }
}
