/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db.tables.daos;


import fi.istrange.traveler.db.tables.Card;
import fi.istrange.traveler.db.tables.records.CardRecord;

import java.math.BigDecimal;
import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CardDao extends DAOImpl<CardRecord, fi.istrange.traveler.db.tables.pojos.Card, Long> {

    /**
     * Create a new CardDao without any configuration
     */
    public CardDao() {
        super(Card.CARD, fi.istrange.traveler.db.tables.pojos.Card.class);
    }

    /**
     * Create a new CardDao with an attached configuration
     */
    public CardDao(Configuration configuration) {
        super(Card.CARD, fi.istrange.traveler.db.tables.pojos.Card.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(fi.istrange.traveler.db.tables.pojos.Card object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.Card> fetchById(Long... values) {
        return fetch(Card.CARD.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public fi.istrange.traveler.db.tables.pojos.Card fetchOneById(Long value) {
        return fetchOne(Card.CARD.ID, value);
    }

    /**
     * Fetch records that have <code>start_time IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.Card> fetchByStartTime(Date... values) {
        return fetch(Card.CARD.START_TIME, values);
    }

    /**
     * Fetch records that have <code>end_time IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.Card> fetchByEndTime(Date... values) {
        return fetch(Card.CARD.END_TIME, values);
    }

    /**
     * Fetch records that have <code>lon IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.Card> fetchByLon(BigDecimal... values) {
        return fetch(Card.CARD.LON, values);
    }

    /**
     * Fetch records that have <code>lat IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.Card> fetchByLat(BigDecimal... values) {
        return fetch(Card.CARD.LAT, values);
    }

    /**
     * Fetch records that have <code>owner_fk IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.Card> fetchByOwnerFk(String... values) {
        return fetch(Card.CARD.OWNER_FK, values);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.Card> fetchByActive(Boolean... values) {
        return fetch(Card.CARD.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.Card> fetchByTitle(String... values) {
        return fetch(Card.CARD.TITLE, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.Card> fetchByDescription(String... values) {
        return fetch(Card.CARD.DESCRIPTION, values);
    }
}
