/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db.tables.daos;


import fi.istrange.traveler.db.tables.GroupCard;
import fi.istrange.traveler.db.tables.records.GroupCardRecord;

import java.math.BigDecimal;
import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupCardDao extends DAOImpl<GroupCardRecord, fi.istrange.traveler.db.tables.pojos.GroupCard, Long> {

    /**
     * Create a new GroupCardDao without any configuration
     */
    public GroupCardDao() {
        super(GroupCard.GROUP_CARD, fi.istrange.traveler.db.tables.pojos.GroupCard.class);
    }

    /**
     * Create a new GroupCardDao with an attached configuration
     */
    public GroupCardDao(Configuration configuration) {
        super(GroupCard.GROUP_CARD, fi.istrange.traveler.db.tables.pojos.GroupCard.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(fi.istrange.traveler.db.tables.pojos.GroupCard object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.GroupCard> fetchById(Long... values) {
        return fetch(GroupCard.GROUP_CARD.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public fi.istrange.traveler.db.tables.pojos.GroupCard fetchOneById(Long value) {
        return fetchOne(GroupCard.GROUP_CARD.ID, value);
    }

    /**
     * Fetch records that have <code>start_time IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.GroupCard> fetchByStartTime(Date... values) {
        return fetch(GroupCard.GROUP_CARD.START_TIME, values);
    }

    /**
     * Fetch records that have <code>end_time IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.GroupCard> fetchByEndTime(Date... values) {
        return fetch(GroupCard.GROUP_CARD.END_TIME, values);
    }

    /**
     * Fetch records that have <code>lon IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.GroupCard> fetchByLon(BigDecimal... values) {
        return fetch(GroupCard.GROUP_CARD.LON, values);
    }

    /**
     * Fetch records that have <code>lat IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.GroupCard> fetchByLat(BigDecimal... values) {
        return fetch(GroupCard.GROUP_CARD.LAT, values);
    }

    /**
     * Fetch records that have <code>owner_fk IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.GroupCard> fetchByOwnerFk(String... values) {
        return fetch(GroupCard.GROUP_CARD.OWNER_FK, values);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.GroupCard> fetchByActive(Boolean... values) {
        return fetch(GroupCard.GROUP_CARD.ACTIVE, values);
    }
}
