/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db.tables.daos;


import fi.istrange.traveler.db.tables.PersonalCard;
import fi.istrange.traveler.db.tables.records.PersonalCardRecord;

import java.math.BigDecimal;
import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonalCardDao extends DAOImpl<PersonalCardRecord, fi.istrange.traveler.db.tables.pojos.PersonalCard, Long> {

    /**
     * Create a new PersonalCardDao without any configuration
     */
    public PersonalCardDao() {
        super(PersonalCard.PERSONAL_CARD, fi.istrange.traveler.db.tables.pojos.PersonalCard.class);
    }

    /**
     * Create a new PersonalCardDao with an attached configuration
     */
    public PersonalCardDao(Configuration configuration) {
        super(PersonalCard.PERSONAL_CARD, fi.istrange.traveler.db.tables.pojos.PersonalCard.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(fi.istrange.traveler.db.tables.pojos.PersonalCard object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.PersonalCard> fetchById(Long... values) {
        return fetch(PersonalCard.PERSONAL_CARD.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public fi.istrange.traveler.db.tables.pojos.PersonalCard fetchOneById(Long value) {
        return fetchOne(PersonalCard.PERSONAL_CARD.ID, value);
    }

    /**
     * Fetch records that have <code>start_time IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.PersonalCard> fetchByStartTime(Date... values) {
        return fetch(PersonalCard.PERSONAL_CARD.START_TIME, values);
    }

    /**
     * Fetch records that have <code>end_time IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.PersonalCard> fetchByEndTime(Date... values) {
        return fetch(PersonalCard.PERSONAL_CARD.END_TIME, values);
    }

    /**
     * Fetch records that have <code>lon IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.PersonalCard> fetchByLon(BigDecimal... values) {
        return fetch(PersonalCard.PERSONAL_CARD.LON, values);
    }

    /**
     * Fetch records that have <code>lat IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.PersonalCard> fetchByLat(BigDecimal... values) {
        return fetch(PersonalCard.PERSONAL_CARD.LAT, values);
    }

    /**
     * Fetch records that have <code>username_fk IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.PersonalCard> fetchByUsernameFk(String... values) {
        return fetch(PersonalCard.PERSONAL_CARD.USERNAME_FK, values);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<fi.istrange.traveler.db.tables.pojos.PersonalCard> fetchByActive(Boolean... values) {
        return fetch(PersonalCard.PERSONAL_CARD.ACTIVE, values);
    }
}
