/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db.tables;


import fi.istrange.traveler.db.Keys;
import fi.istrange.traveler.db.Public;
import fi.istrange.traveler.db.tables.records.CardUserRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CardUser extends TableImpl<CardUserRecord> {

    private static final long serialVersionUID = 116868998;

    /**
     * The reference instance of <code>public.card_user</code>
     */
    public static final CardUser CARD_USER = new CardUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CardUserRecord> getRecordType() {
        return CardUserRecord.class;
    }

    /**
     * The column <code>public.card_user.card_id</code>.
     */
    public final TableField<CardUserRecord, Long> CARD_ID = createField("card_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.card_user.username</code>.
     */
    public final TableField<CardUserRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(80), this, "");

    /**
     * Create a <code>public.card_user</code> table reference
     */
    public CardUser() {
        this("card_user", null);
    }

    /**
     * Create an aliased <code>public.card_user</code> table reference
     */
    public CardUser(String alias) {
        this(alias, CARD_USER);
    }

    private CardUser(String alias, Table<CardUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private CardUser(String alias, Table<CardUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CardUserRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CardUserRecord, ?>>asList(Keys.CARD_USER__CARD_USER_CARD_ID_FKEY, Keys.CARD_USER__CARD_USER_USERNAME_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardUser as(String alias) {
        return new CardUser(alias, this);
    }

    public CardUser rename(String name) {
        return new CardUser(name, null);
    }
}
