/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CardUser implements Serializable {

    private static final long serialVersionUID = -2056935920;

    private Long   cardId;
    private String username;

    public CardUser() {}

    public CardUser(CardUser value) {
        this.cardId = value.cardId;
        this.username = value.username;
    }

    public CardUser(
        Long   cardId,
        String username
    ) {
        this.cardId = cardId;
        this.username = username;
    }

    public Long getCardId() {
        return this.cardId;
    }

    public void setCardId(Long cardId) {
        this.cardId = cardId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CardUser (");

        sb.append(cardId);
        sb.append(", ").append(username);

        sb.append(")");
        return sb.toString();
    }
}
