/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CardPhoto implements Serializable {

    private static final long serialVersionUID = -555857404;

    private Long cardId;
    private Long photo;

    public CardPhoto() {}

    public CardPhoto(CardPhoto value) {
        this.cardId = value.cardId;
        this.photo = value.photo;
    }

    public CardPhoto(
        Long cardId,
        Long photo
    ) {
        this.cardId = cardId;
        this.photo = photo;
    }

    public Long getCardId() {
        return this.cardId;
    }

    public void setCardId(Long cardId) {
        this.cardId = cardId;
    }

    public Long getPhoto() {
        return this.photo;
    }

    public void setPhoto(Long photo) {
        this.photo = photo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CardPhoto (");

        sb.append(cardId);
        sb.append(", ").append(photo);

        sb.append(")");
        return sb.toString();
    }
}
