/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupCard implements Serializable {

    private static final long serialVersionUID = 1240395418;

    private Long id;

    public GroupCard() {}

    public GroupCard(GroupCard value) {
        this.id = value.id;
    }

    public GroupCard(
        Long id
    ) {
        this.id = id;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GroupCard (");

        sb.append(id);

        sb.append(")");
        return sb.toString();
    }
}
