/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Match implements Serializable {

    private static final long serialVersionUID = 324450544;

    private Long    likerCardId;
    private Long    likedCardId;
    private Boolean likeDecision;

    public Match() {}

    public Match(Match value) {
        this.likerCardId = value.likerCardId;
        this.likedCardId = value.likedCardId;
        this.likeDecision = value.likeDecision;
    }

    public Match(
        Long    likerCardId,
        Long    likedCardId,
        Boolean likeDecision
    ) {
        this.likerCardId = likerCardId;
        this.likedCardId = likedCardId;
        this.likeDecision = likeDecision;
    }

    public Long getLikerCardId() {
        return this.likerCardId;
    }

    public void setLikerCardId(Long likerCardId) {
        this.likerCardId = likerCardId;
    }

    public Long getLikedCardId() {
        return this.likedCardId;
    }

    public void setLikedCardId(Long likedCardId) {
        this.likedCardId = likedCardId;
    }

    public Boolean getLikeDecision() {
        return this.likeDecision;
    }

    public void setLikeDecision(Boolean likeDecision) {
        this.likeDecision = likeDecision;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Match (");

        sb.append(likerCardId);
        sb.append(", ").append(likedCardId);
        sb.append(", ").append(likeDecision);

        sb.append(")");
        return sb.toString();
    }
}
