/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonalCard implements Serializable {

    private static final long serialVersionUID = 452068484;

    private Long   id;
    private Date   startTime;
    private Date   endTime;
    private Long   lon;
    private Long   lat;
    private String usernameFk;

    public PersonalCard() {}

    public PersonalCard(PersonalCard value) {
        this.id = value.id;
        this.startTime = value.startTime;
        this.endTime = value.endTime;
        this.lon = value.lon;
        this.lat = value.lat;
        this.usernameFk = value.usernameFk;
    }

    public PersonalCard(
        Long   id,
        Date   startTime,
        Date   endTime,
        Long   lon,
        Long   lat,
        String usernameFk
    ) {
        this.id = id;
        this.startTime = startTime;
        this.endTime = endTime;
        this.lon = lon;
        this.lat = lat;
        this.usernameFk = usernameFk;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public Long getLon() {
        return this.lon;
    }

    public void setLon(Long lon) {
        this.lon = lon;
    }

    public Long getLat() {
        return this.lat;
    }

    public void setLat(Long lat) {
        this.lat = lat;
    }

    public String getUsernameFk() {
        return this.usernameFk;
    }

    public void setUsernameFk(String usernameFk) {
        this.usernameFk = usernameFk;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PersonalCard (");

        sb.append(id);
        sb.append(", ").append(startTime);
        sb.append(", ").append(endTime);
        sb.append(", ").append(lon);
        sb.append(", ").append(lat);
        sb.append(", ").append(usernameFk);

        sb.append(")");
        return sb.toString();
    }
}
