/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCredentials implements Serializable {

    private static final long serialVersionUID = 1675298084;

    private String  username;
    private String  password;
    private Boolean active;

    public UserCredentials() {}

    public UserCredentials(UserCredentials value) {
        this.username = value.username;
        this.password = value.password;
        this.active = value.active;
    }

    public UserCredentials(
        String  username,
        String  password,
        Boolean active
    ) {
        this.username = username;
        this.password = password;
        this.active = active;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserCredentialsView (");

        sb.append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(active);

        sb.append(")");
        return sb.toString();
    }
}
