/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPhoto implements Serializable {

    private static final long serialVersionUID = 824765137;

    private String username;
    private Long   photo;

    public UserPhoto() {}

    public UserPhoto(UserPhoto value) {
        this.username = value.username;
        this.photo = value.photo;
    }

    public UserPhoto(
        String username,
        Long   photo
    ) {
        this.username = username;
        this.photo = photo;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Long getPhoto() {
        return this.photo;
    }

    public void setPhoto(Long photo) {
        this.photo = photo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserPhoto (");

        sb.append(username);
        sb.append(", ").append(photo);

        sb.append(")");
        return sb.toString();
    }
}
