/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db.tables.records;


import fi.istrange.traveler.db.tables.CardPhoto;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CardPhotoRecord extends TableRecordImpl<CardPhotoRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 185368156;

    /**
     * Setter for <code>public.card_photo.card_id</code>.
     */
    public void setCardId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.card_photo.card_id</code>.
     */
    public Long getCardId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.card_photo.photo</code>.
     */
    public void setPhoto(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.card_photo.photo</code>.
     */
    public Long getPhoto() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CardPhoto.CARD_PHOTO.CARD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return CardPhoto.CARD_PHOTO.PHOTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getCardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardPhotoRecord value1(Long value) {
        setCardId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardPhotoRecord value2(Long value) {
        setPhoto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardPhotoRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CardPhotoRecord
     */
    public CardPhotoRecord() {
        super(CardPhoto.CARD_PHOTO);
    }

    /**
     * Create a detached, initialised CardPhotoRecord
     */
    public CardPhotoRecord(Long cardId, Long photo) {
        super(CardPhoto.CARD_PHOTO);

        set(0, cardId);
        set(1, photo);
    }
}
