/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db.tables.records;


import fi.istrange.traveler.db.tables.CardUser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CardUserRecord extends TableRecordImpl<CardUserRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 477010243;

    /**
     * Setter for <code>public.card_user.card_id</code>.
     */
    public void setCardId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.card_user.card_id</code>.
     */
    public Long getCardId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.card_user.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.card_user.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CardUser.CARD_USER.CARD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CardUser.CARD_USER.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getCardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardUserRecord value1(Long value) {
        setCardId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardUserRecord value2(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardUserRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CardUserRecord
     */
    public CardUserRecord() {
        super(CardUser.CARD_USER);
    }

    /**
     * Create a detached, initialised CardUserRecord
     */
    public CardUserRecord(Long cardId, String username) {
        super(CardUser.CARD_USER);

        set(0, cardId);
        set(1, username);
    }
}
