/*
 * This file is generated by jOOQ.
*/
package fi.istrange.traveler.db.tables.records;


import fi.istrange.traveler.db.tables.UserPhoto;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPhotoRecord extends TableRecordImpl<UserPhotoRecord> implements Record2<String, Long> {

    private static final long serialVersionUID = -286578205;

    /**
     * Setter for <code>public.user_photo.username</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_photo.username</code>.
     */
    public String getUsername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user_photo.photo</code>.
     */
    public void setPhoto(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_photo.photo</code>.
     */
    public Long getPhoto() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return UserPhoto.USER_PHOTO.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return UserPhoto.USER_PHOTO.PHOTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPhotoRecord value1(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPhotoRecord value2(Long value) {
        setPhoto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPhotoRecord values(String value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserPhotoRecord
     */
    public UserPhotoRecord() {
        super(UserPhoto.USER_PHOTO);
    }

    /**
     * Create a detached, initialised UserPhotoRecord
     */
    public UserPhotoRecord(String username, Long photo) {
        super(UserPhoto.USER_PHOTO);

        set(0, username);
        set(1, photo);
    }
}
